### ISSUE TITLE
Cannot Login Arizen wallet

### ISSUE THREAD

**Issue by supermera** [HorizenOfficial/arizen#440]
I trying to restore my ZEN wallet with uatw file.
When trying to login - Wallet with this name does not exist.
I tried several time retype name double checked file name and nothing.

**Comment by uanl979** [comment]
Hey there @supermera 

We have a support system in Horizen, called Helpdesk. Do you want me to raise a ticket on the Helpdesk on your behalf? I just need an email, or you could raise a ticket at support.horizen.io.

Regards
Rubén

**Comment by uanl979** [comment]
Hey just following up, have you already solved you issue?

**Comment by uanl979** [comment]
Closing this issue, in you are still having issues, please raise it at our Helpdeks at support.horizen.io
